import { AchievementObjectType } from "./AchievementModuleTypes";

const InitAchievements: AchievementObjectType = {
  Cook: false,
  TidyChef: false,
  CleanEater: false,
  CleanSlate: false,
  CleanSweep: false,
  KitchenZen: false,
  BraveEater: false,
  MasterChef: false,
  StylishChef: false,
  PerfectDish: false,
  WildHarvest: false,
  SqueakyClean: false,
  CreativeCook: false,
  MadScientist: false,
  HygieneMaster: false,
  TidyHairHero: false,
  SlipFreeChef: false,
  CleanGardener: false,
  SunnyGardener: false,
  NervesOfSteel: false,
  ApprenticeCook: false,
  ItchyEncounter: false,
  GardenExplorer: false,
  MasterGardener: false,
  KitchenExplorer: false,
  PrecisionCutter: false,
  CuriousGardener: false,
  GreenThumbForever: false,
  OutOfComfortZone: false,
  FunctionalWardrobe: false,
  GreenThumbProtector: false,
  WorkSmarterNotHarder: false,
  AwarenessAndCommunication: false,
};

export { InitAchievements };
