import { AchievementObjectType } from "./AchievementModuleTypes";

const InitAchievements: AchievementObjectType = {
  Cook: false,
  "Tidy Chef": false,
  "Clean Eater": false,
  "Clean Slate": false,
  "Clean Sweep": false,
  "Kitchen Zen": false,
  "Brave Eater": false,
  "Master Chef": false,
  "Stylish Chef": false,
  "Perfect Dish": false,
  "Wild Harvest": false,
  "Squeaky Clean": false,
  "Creative Cook": false,
  "Mad Scientist": false,
  "Hygiene Master": false,
  "Tidy Hair Hero": false,
  "Slip-Free Chef": false,
  "Clean Gardener": false,
  "Sunny Gardener": false,
  "Nerves of Steel": false,
  "Apprentice Cook": false,
  "Itchy Encounter": false,
  "Garden Explorer": false,
  "Master Gardener": false,
  "Kitchen Explorer": false,
  "Precision Cutter": false,
  "Curious Gardener": false,
  "Green Thumb Forever": false,
  "Out of Comfort Zone": false,
  "Functional Wardrobe": false,
  "Green Thumb Protector": false,
  "Work Smarter Not Harder": false,
  "Awareness and Communication": false,
};

export { InitAchievements };
