const FOV_PRESET_ONE = 35;
const FOV_PRESET_TWO = 20.4;
const FOV_PRESET_ZERO = 43;

const GATE_FOV = FOV_PRESET_ZERO;
const BIGTREE_FOV = FOV_PRESET_ONE;
const TOOLRACK_FOV = FOV_PRESET_ONE;
const PLANTBOX_FOV = FOV_PRESET_ONE;
const GARDENVIEW_FOV = FOV_PRESET_TWO;
const GARDENHOSE_FOV = FOV_PRESET_ONE;
const SOILCORNER_FOV = FOV_PRESET_ONE;
const KITCHENVIEW_FOV = FOV_PRESET_ZERO;

export {
  GATE_FOV,
  BIGTREE_FOV,
  TOOLRACK_FOV,
  PLANTBOX_FOV,
  GARDENHOSE_FOV,
  SOILCORNER_FOV,
  GARDENVIEW_FOV,
  KITCHENVIEW_FOV,
};
