/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 pccc_garden_v001.glb --transform --precision=10 --shadows --keepnames --meta --types
*/

import { useGLTF } from "@react-three/drei";
import { memo } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh090: THREE.Mesh;
    Mesh090_1: THREE.Mesh;
    Mesh090_2: THREE.Mesh;
    Mesh090_3: THREE.Mesh;
    Mesh090_4: THREE.Mesh;
    Mesh090_5: THREE.Mesh;
    Mesh090_6: THREE.Mesh;
    Mesh090_7: THREE.Mesh;
    Mesh090_8: THREE.Mesh;
    Mesh090_9: THREE.Mesh;
    Mesh090_10: THREE.Mesh;
    Mesh090_11: THREE.Mesh;
    Mesh090_12: THREE.Mesh;
    Mesh090_13: THREE.Mesh;
    Mesh090_14: THREE.Mesh;
    Mesh090_15: THREE.Mesh;
    Mesh090_16: THREE.Mesh;
    Mesh090_17: THREE.Mesh;
    Mesh090_18: THREE.Mesh;
    Mesh090_19: THREE.Mesh;
    Mesh090_20: THREE.Mesh;
    Mesh090_21: THREE.Mesh;
    Mesh090_22: THREE.Mesh;
    Mesh090_23: THREE.Mesh;
    Mesh090_24: THREE.Mesh;
  };
  materials: {
    Beige: THREE.MeshStandardMaterial;
    lambert2: THREE.MeshStandardMaterial;
    Dark_Brown: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    Brown: THREE.MeshStandardMaterial;
    Dark_Green: THREE.MeshStandardMaterial;
    Grey: THREE.MeshStandardMaterial;
    Light_Green: THREE.MeshStandardMaterial;
    Orange: THREE.MeshStandardMaterial;
    Light_Beige: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    ["Dark_Green.001"]: THREE.MeshStandardMaterial;
    Water: THREE.MeshStandardMaterial;
    farm_pack: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
    Yellow: THREE.MeshStandardMaterial;
  };
};

const Garden = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(
    "/game_assets/models/pccc_garden_v001-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="MergedEnvironment"
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.0099999998, 0.0099999988, 0.0099999988]}
        userData={{ name: "MergedEnvironment" }}
      >
        <mesh
          name="Mesh090"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090.geometry}
          material={materials.Beige}
        />
        <mesh
          name="Mesh090_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_1.geometry}
          material={materials.lambert2}
        />
        <mesh
          name="Mesh090_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_2.geometry}
          material={materials.Dark_Brown}
        />
        <mesh
          name="Mesh090_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_3.geometry}
          material={materials.Metal}
        />
        <mesh
          name="Mesh090_4"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_4.geometry}
          material={materials.Brown}
        />
        <mesh
          name="Mesh090_5"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_5.geometry}
          material={materials.Dark_Green}
        />
        <mesh
          name="Mesh090_6"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_6.geometry}
          material={materials.Grey}
        />
        <mesh
          name="Mesh090_7"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_7.geometry}
          material={materials.Light_Green}
        />
        <mesh
          name="Mesh090_8"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_8.geometry}
          material={materials.Orange}
        />
        <mesh
          name="Mesh090_9"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_9.geometry}
          material={materials.Light_Beige}
        />
        <mesh
          name="Mesh090_10"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_10.geometry}
          material={materials.Glass}
        />
        <mesh
          name="Mesh090_11"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_11.geometry}
          material={materials["Dark_Green.001"]}
        />
        <mesh
          name="Mesh090_12"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_12.geometry}
          material={materials.Water}
        />
        <mesh
          name="Mesh090_13"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_13.geometry}
          material={materials.farm_pack}
        />
        <mesh
          name="Mesh090_14"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_14.geometry}
          material={materials.Red}
        />
        <mesh
          name="Mesh090_15"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_15.geometry}
          material={materials.Dark_Brown}
        />
        <mesh
          name="Mesh090_16"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_16.geometry}
          material={materials.Light_Green}
        />
        <mesh
          name="Mesh090_17"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_17.geometry}
          material={materials.Dark_Green}
        />
        <mesh
          name="Mesh090_18"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_18.geometry}
          material={materials.Metal}
        />
        <mesh
          name="Mesh090_19"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_19.geometry}
          material={materials.Yellow}
        />
        <mesh
          name="Mesh090_20"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_20.geometry}
          material={materials.Beige}
        />
        <mesh
          name="Mesh090_21"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_21.geometry}
          material={materials.Light_Beige}
        />
        <mesh
          name="Mesh090_22"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_22.geometry}
          material={materials.Orange}
        />
        <mesh
          name="Mesh090_23"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_23.geometry}
          material={materials.Dark_Green}
        />
        <mesh
          name="Mesh090_24"
          castShadow
          receiveShadow
          geometry={nodes.Mesh090_24.geometry}
          material={materials.Dark_Brown}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/game_assets/models/pccc_garden_v001-transformed.glb");

export default memo(Garden);
