/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Garden_Test.glb --transform --precision=10 --shadows --keepnames --meta --types
*/

import { useGLTF } from "@react-three/drei";
import { memo } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh571: THREE.Mesh;
    Mesh571_1: THREE.Mesh;
    grass_strand: THREE.Mesh;
    Mesh225: THREE.Mesh;
    Mesh225_1: THREE.Mesh;
    SM_Prop_Beehive_01: THREE.Mesh;
    SM_Prop_Beehive_04: THREE.Mesh;
    SM_Prop_Chicken_Coop_03: THREE.Mesh;
    SM_Prop_Crate_01: THREE.Mesh;
    Mesh182: THREE.Mesh;
    Mesh182_1: THREE.Mesh;
    garden_ALL_FARM_PACK_NEW_GARDEN_FENCE_SM_Prop_Fence_Fan_01d6e25: THREE.Mesh;
    polySurface484: THREE.Mesh;
    polySurface482: THREE.Mesh;
    polySurface554: THREE.Mesh;
    polySurface483: THREE.Mesh;
    polySurface555: THREE.Mesh;
    polySurface488: THREE.Mesh;
    polySurface556: THREE.Mesh;
    polySurface474: THREE.Mesh;
    polySurface552: THREE.Mesh;
    polySurface553: THREE.Mesh;
    Mesh162: THREE.Mesh;
    Mesh162_1: THREE.Mesh;
    dark_tiles: THREE.Mesh;
    sidewalk: THREE.Mesh;
    SM_Prop_GrainBag_06: THREE.Mesh;
    SM_Prop_GrainBag_07: THREE.Mesh;
    SM_Prop_GrainBag_09: THREE.Mesh;
    SM_Prop_GrainBag_15: THREE.Mesh;
    SM_Prop_GrainBag_16: THREE.Mesh;
    Mesh193: THREE.Mesh;
    Mesh193_1: THREE.Mesh;
    Wheelbarrow1: THREE.Mesh;
    polySurface495: THREE.Mesh;
    SM_Bld_Shelter_03: THREE.Mesh;
    SM_Prop_Rack_02: THREE.Mesh;
    SM_Prop_Rubbish_Pile_06: THREE.Mesh;
    SM_Prop_Rusted_Drum_02: THREE.Mesh;
    SM_Prop_Wheelbarrow_Wheel_02: THREE.Mesh;
    SM_Env_Dirt_Rows_Skirt_21: THREE.Mesh;
    SM_Env_Dirt_Rows_Skirt_22: THREE.Mesh;
    SM_Env_Dirt_Rows_Skirt_23: THREE.Mesh;
    SM_Env_Dirt_Rows_Skirt_24: THREE.Mesh;
    SM_Env_Dirt_Rows_Skirt_25: THREE.Mesh;
    SM_Env_Dirt_Rows_Skirt_26: THREE.Mesh;
    SM_Env_Dirt_Rows_Skirt_27: THREE.Mesh;
    SM_Env_Dirt_Rows_Skirt_28: THREE.Mesh;
    SM_Prop_Scarecrow_02: THREE.Mesh;
    Mesh503_1: THREE.Mesh;
    Mesh503_2: THREE.Mesh;
    Mesh503_3: THREE.Mesh;
    SM_Prop_Tool_Hoe_02001: THREE.Mesh;
    SM_Prop_Tool_Pitchfork_02001: THREE.Mesh;
    SM_Prop_Tool_Rake_02001: THREE.Mesh;
    SM_Prop_Tool_Spade_02001: THREE.Mesh;
    polySurface546: THREE.Mesh;
    SM_Bld_ProduceStand_04: THREE.Mesh;
    SM_Prop_Tool_Hoe_02: THREE.Mesh;
    SM_Prop_Tool_Pitchfork_02: THREE.Mesh;
    SM_Prop_Tool_Rake_02: THREE.Mesh;
    SM_Prop_Tool_Spade_02: THREE.Mesh;
    polySurface42: THREE.Mesh;
    polySurface45: THREE.Mesh;
    tool_shed_rack_SHOPS_PACK: THREE.Mesh;
    SM_Prop_Tool_Hoe_02002: THREE.Mesh;
    SM_Prop_Tool_Pitchfork_02002: THREE.Mesh;
    SM_Prop_Tool_Rake_02002: THREE.Mesh;
    SM_Prop_Tool_Spade_02002: THREE.Mesh;
    SM_Prop_Tool_Axe_02: THREE.Mesh;
    SM_Prop_Tool_Bucket_02: THREE.Mesh;
    SM_Prop_ToolBox_03: THREE.Mesh;
    SM_Prop_SeedPacket_03: THREE.Mesh;
    SM_Prop_SeedPacket_04: THREE.Mesh;
    SM_Prop_SeedPacket_05: THREE.Mesh;
    SM_Prop_SeedPacket_06: THREE.Mesh;
    SM_Prop_SeedPacket_07: THREE.Mesh;
    tool_shed_table: THREE.Mesh;
    Mesh482: THREE.Mesh;
    Mesh483: THREE.Mesh;
    Mesh484: THREE.Mesh;
    Mesh486: THREE.Mesh;
    Mesh695: THREE.Mesh;
    Mesh696: THREE.Mesh;
    tools_TOWN_PACK_v001_Mesh485: THREE.Mesh;
    pCylinder26: THREE.Mesh;
    polySurface56: THREE.Mesh;
    polySurface59: THREE.Mesh;
    polySurface61: THREE.Mesh;
    polySurface62: THREE.Mesh;
    polySurface63: THREE.Mesh;
    polySurface64: THREE.Mesh;
    polySurface65: THREE.Mesh;
    SM_Prop_Tool_Axe_02001: THREE.Mesh;
    SM_Prop_Tool_Bucket_02001: THREE.Mesh;
    SM_Prop_ToolBox_03001: THREE.Mesh;
    SM_Prop_SeedPacket_03001: THREE.Mesh;
    SM_Prop_SeedPacket_04001: THREE.Mesh;
    SM_Prop_SeedPacket_05001: THREE.Mesh;
    SM_Prop_SeedPacket_06001: THREE.Mesh;
    SM_Prop_SeedPacket_07001: THREE.Mesh;
    Mesh482001: THREE.Mesh;
    Mesh483001: THREE.Mesh;
    Mesh484001: THREE.Mesh;
    Mesh485: THREE.Mesh;
    Mesh486001: THREE.Mesh;
    Mesh695001: THREE.Mesh;
    Mesh696001: THREE.Mesh;
    Mesh710: THREE.Mesh;
    Mesh711: THREE.Mesh;
    Mesh712: THREE.Mesh;
    Mesh713: THREE.Mesh;
    Mesh714: THREE.Mesh;
    Mesh715: THREE.Mesh;
    Mesh716: THREE.Mesh;
    Mesh717: THREE.Mesh;
    Mesh718: THREE.Mesh;
    Mesh719: THREE.Mesh;
    Mesh720: THREE.Mesh;
    Mesh375: THREE.Mesh;
    Mesh376: THREE.Mesh;
    Mesh377: THREE.Mesh;
    Mesh678: THREE.Mesh;
    Mesh679: THREE.Mesh;
    Mesh680: THREE.Mesh;
    Mesh681: THREE.Mesh;
    Mesh682: THREE.Mesh;
    Mesh683: THREE.Mesh;
    Mesh684: THREE.Mesh;
    Mesh685: THREE.Mesh;
    Mesh698: THREE.Mesh;
    Mesh699: THREE.Mesh;
    Mesh700: THREE.Mesh;
    Mesh702: THREE.Mesh;
    Mesh703: THREE.Mesh;
    Mesh704: THREE.Mesh;
    Mesh705: THREE.Mesh;
    Mesh706: THREE.Mesh;
    Mesh707: THREE.Mesh;
    Mesh708: THREE.Mesh;
    Mesh709: THREE.Mesh;
    Mesh492: THREE.Mesh;
    Mesh493: THREE.Mesh;
    Mesh494: THREE.Mesh;
    Mesh495: THREE.Mesh;
    Mesh496: THREE.Mesh;
    Mesh497: THREE.Mesh;
    Mesh498: THREE.Mesh;
    Mesh499: THREE.Mesh;
    Mesh500: THREE.Mesh;
    Mesh501: THREE.Mesh;
    Mesh502: THREE.Mesh;
    Mesh503: THREE.Mesh;
    Mesh504: THREE.Mesh;
    Mesh505: THREE.Mesh;
    Mesh506: THREE.Mesh;
    Mesh507: THREE.Mesh;
    Mesh508: THREE.Mesh;
    Mesh509: THREE.Mesh;
    Mesh510: THREE.Mesh;
    Mesh511: THREE.Mesh;
    Mesh512: THREE.Mesh;
    Mesh513: THREE.Mesh;
    Mesh514: THREE.Mesh;
    Mesh515: THREE.Mesh;
    Mesh516: THREE.Mesh;
    Mesh517: THREE.Mesh;
    Mesh518: THREE.Mesh;
    Mesh519: THREE.Mesh;
    Mesh520: THREE.Mesh;
    Mesh521: THREE.Mesh;
    flower_box: THREE.Mesh;
    Mesh475: THREE.Mesh;
    Mesh477: THREE.Mesh;
    Mesh487: THREE.Mesh;
    Mesh488: THREE.Mesh;
    Mesh489: THREE.Mesh;
    ground: THREE.Mesh;
  };
  materials: {
    lambert1: THREE.MeshStandardMaterial;
    town_pack: THREE.MeshStandardMaterial;
    farm_pack: THREE.MeshStandardMaterial;
    shops_pack: THREE.MeshStandardMaterial;
    farm_sign_mat: THREE.MeshStandardMaterial;
  };
};

const Garden = (props: JSX.IntrinsicElements["group"]) => {
  const { nodes, materials } = useGLTF(
    "/game_assets/models/Garden_Test-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="pccc_garden"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0099999998}
        userData={{ name: "pccc_garden" }}
      >
        <group
          name="env_foliage_and_house"
          userData={{ name: "env_foliage_and_house" }}
        >
          <group name="trees" userData={{ name: "trees" }}>
            <group
              name="Trees"
              position={[-10.2397460938, 189.2687988281, -214.9518585205]}
              rotation={[0, 0, -2.0689502533]}
              scale={[3.81397295, 3.81397295, 2.2308402061]}
              userData={{ name: "Trees" }}
            >
              <mesh
                name="Mesh571"
                castShadow
                receiveShadow
                geometry={nodes.Mesh571.geometry}
                material={materials.town_pack}
              />
              <mesh
                name="Mesh571_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh571_1.geometry}
                material={materials.lambert1}
              />
            </group>
          </group>
          <mesh
            name="grass_strand"
            castShadow
            receiveShadow
            geometry={nodes.grass_strand.geometry}
            material={materials.town_pack}
            userData={{ name: "grass_strand" }}
          />
          <group name="house" userData={{ name: "house" }}>
            <mesh
              name="Mesh225"
              castShadow
              receiveShadow
              geometry={nodes.Mesh225.geometry}
              material={materials.farm_pack}
            />
            <mesh
              name="Mesh225_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh225_1.geometry}
              material={materials.town_pack}
            />
          </group>
        </group>
        <group name="farmPack" userData={{ name: "farmPack" }}>
          <group name="bee_stuff" userData={{ name: "bee_stuff" }}>
            <mesh
              name="SM_Prop_Beehive_01"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Beehive_01.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Beehive_01" }}
            />
            <mesh
              name="SM_Prop_Beehive_04"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Beehive_04.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Beehive_04" }}
            />
            <mesh
              name="SM_Prop_Chicken_Coop_03"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Chicken_Coop_03.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Chicken_Coop_03" }}
            />
            <mesh
              name="SM_Prop_Crate_01"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Crate_01.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Crate_01" }}
            />
          </group>
          <group
            name="garden_big_plant_label_sign"
            userData={{ name: "garden_big_plant_label_sign" }}
          >
            <group name="group75" userData={{ name: "group75" }}>
              <mesh
                name="polySurface482"
                castShadow
                receiveShadow
                geometry={nodes.polySurface482.geometry}
                material={materials.farm_sign_mat}
                userData={{ name: "polySurface482" }}
              />
              <mesh
                name="polySurface554"
                castShadow
                receiveShadow
                geometry={nodes.polySurface554.geometry}
                material={materials.farm_pack}
                userData={{ name: "polySurface554" }}
              />
            </group>
            <group name="group76" userData={{ name: "group76" }}>
              <mesh
                name="polySurface483"
                castShadow
                receiveShadow
                geometry={nodes.polySurface483.geometry}
                material={materials.farm_sign_mat}
                userData={{ name: "polySurface483" }}
              />
              <mesh
                name="polySurface555"
                castShadow
                receiveShadow
                geometry={nodes.polySurface555.geometry}
                material={materials.farm_pack}
                userData={{ name: "polySurface555" }}
              />
            </group>
            <group name="group77" userData={{ name: "group77" }}>
              <mesh
                name="polySurface488"
                castShadow
                receiveShadow
                geometry={nodes.polySurface488.geometry}
                material={materials.farm_sign_mat}
                userData={{ name: "polySurface488" }}
              />
              <mesh
                name="polySurface556"
                castShadow
                receiveShadow
                geometry={nodes.polySurface556.geometry}
                material={materials.farm_pack}
                userData={{ name: "polySurface556" }}
              />
            </group>
            <mesh
              name="polySurface484"
              castShadow
              receiveShadow
              geometry={nodes.polySurface484.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface484" }}
            />
          </group>
          <group name="location_signs" userData={{ name: "location_signs" }}>
            <mesh
              name="polySurface474"
              castShadow
              receiveShadow
              geometry={nodes.polySurface474.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface474" }}
            />
            <mesh
              name="polySurface552"
              castShadow
              receiveShadow
              geometry={nodes.polySurface552.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface552" }}
            />
            <mesh
              name="polySurface553"
              castShadow
              receiveShadow
              geometry={nodes.polySurface553.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface553" }}
            />
          </group>
          <group name="sidewalk_ground" userData={{ name: "sidewalk_ground" }}>
            <mesh
              name="dark_tiles"
              castShadow
              receiveShadow
              geometry={nodes.dark_tiles.geometry}
              material={materials.farm_pack}
              userData={{ name: "dark_tiles" }}
            />
            <mesh
              name="sidewalk"
              castShadow
              receiveShadow
              geometry={nodes.sidewalk.geometry}
              material={materials.farm_pack}
              position={[-12.1208496094, 1585.69921875, -13.2585830688]}
              rotation={[0, 0, -Math.PI / 2]}
              userData={{ name: "sidewalk" }}
            />
          </group>
          <group name="soil_area001" userData={{ name: "soil_area.001" }}>
            <group name="soil_bag" userData={{ name: "soil_bag" }}>
              <group name="group68" userData={{ name: "group68" }}>
                <mesh
                  name="SM_Prop_GrainBag_06"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_GrainBag_06.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_GrainBag_06" }}
                />
                <mesh
                  name="SM_Prop_GrainBag_07"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_GrainBag_07.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_GrainBag_07" }}
                />
                <mesh
                  name="SM_Prop_GrainBag_09"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_GrainBag_09.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_GrainBag_09" }}
                />
              </group>
              <mesh
                name="SM_Prop_GrainBag_15"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_GrainBag_15.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_GrainBag_15" }}
              />
              <mesh
                name="SM_Prop_GrainBag_16"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_GrainBag_16.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_GrainBag_16" }}
              />
            </group>
            <mesh
              name="Wheelbarrow1"
              castShadow
              receiveShadow
              geometry={nodes.Wheelbarrow1.geometry}
              material={materials.farm_pack}
              userData={{ name: "Wheelbarrow1" }}
            />
            <group
              name="SM_Bld_ProduceStand_03"
              userData={{ name: "SM_Bld_ProduceStand_03" }}
            >
              <mesh
                name="Mesh193"
                castShadow
                receiveShadow
                geometry={nodes.Mesh193.geometry}
                material={materials.farm_pack}
              />
              <mesh
                name="Mesh193_1"
                castShadow
                receiveShadow
                geometry={nodes.Mesh193_1.geometry}
                material={materials.town_pack}
              />
            </group>
          </group>
          <group name="tool_shed" userData={{ name: "tool_shed" }}>
            <mesh
              name="polySurface495"
              castShadow
              receiveShadow
              geometry={nodes.polySurface495.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface495" }}
            />
            <mesh
              name="SM_Bld_Shelter_03"
              castShadow
              receiveShadow
              geometry={nodes.SM_Bld_Shelter_03.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Bld_Shelter_03" }}
            />
            <mesh
              name="SM_Prop_Rack_02"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Rack_02.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Rack_02" }}
            />
            <mesh
              name="SM_Prop_Rubbish_Pile_06"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Rubbish_Pile_06.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Rubbish_Pile_06" }}
            />
            <mesh
              name="SM_Prop_Rusted_Drum_02"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Rusted_Drum_02.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Rusted_Drum_02" }}
            />
            <mesh
              name="SM_Prop_Wheelbarrow_Wheel_02"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Wheelbarrow_Wheel_02.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Wheelbarrow_Wheel_02" }}
            />
          </group>
          <group
            name="SM_Prop_Chair_02"
            userData={{ name: "SM_Prop_Chair_02" }}
          >
            <mesh
              name="Mesh182"
              castShadow
              receiveShadow
              geometry={nodes.Mesh182.geometry}
              material={materials.farm_pack}
            />
            <mesh
              name="Mesh182_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh182_1.geometry}
              material={materials.shops_pack}
            />
          </group>
          <mesh
            name="garden_ALL_FARM_PACK_NEW_GARDEN_FENCE_SM_Prop_Fence_Fan_01d6e25"
            castShadow
            receiveShadow
            geometry={
              nodes
                .garden_ALL_FARM_PACK_NEW_GARDEN_FENCE_SM_Prop_Fence_Fan_01d6e25
                .geometry
            }
            material={materials.farm_pack}
            userData={{
              name: "garden_ALL_FARM_PACK_NEW_GARDEN_FENCE_SM_Prop_Fence_Fan_01d6e25",
            }}
          />
          <group name="Pond" userData={{ name: "Pond" }}>
            <mesh
              name="Mesh162"
              castShadow
              receiveShadow
              geometry={nodes.Mesh162.geometry}
              material={materials.farm_pack}
            />
            <mesh
              name="Mesh162_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh162_1.geometry}
              material={materials.shops_pack}
            />
          </group>
        </group>
        <group
          name="gardenBOX_VERSIONS"
          userData={{ name: "gardenBOX_VERSIONS" }}
        >
          <group
            name="garden_FARM_PACK_v001"
            userData={{ name: "garden_FARM_PACK_v001" }}
          >
            <group
              name="garden_box_and_dirt"
              userData={{ name: "garden_box_and_dirt" }}
            >
              <mesh
                name="SM_Env_Dirt_Rows_Skirt_21"
                castShadow
                receiveShadow
                geometry={nodes.SM_Env_Dirt_Rows_Skirt_21.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Env_Dirt_Rows_Skirt_21" }}
              />
              <mesh
                name="SM_Env_Dirt_Rows_Skirt_22"
                castShadow
                receiveShadow
                geometry={nodes.SM_Env_Dirt_Rows_Skirt_22.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Env_Dirt_Rows_Skirt_22" }}
              />
              <mesh
                name="SM_Env_Dirt_Rows_Skirt_23"
                castShadow
                receiveShadow
                geometry={nodes.SM_Env_Dirt_Rows_Skirt_23.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Env_Dirt_Rows_Skirt_23" }}
              />
              <mesh
                name="SM_Env_Dirt_Rows_Skirt_24"
                castShadow
                receiveShadow
                geometry={nodes.SM_Env_Dirt_Rows_Skirt_24.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Env_Dirt_Rows_Skirt_24" }}
              />
              <mesh
                name="SM_Env_Dirt_Rows_Skirt_25"
                castShadow
                receiveShadow
                geometry={nodes.SM_Env_Dirt_Rows_Skirt_25.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Env_Dirt_Rows_Skirt_25" }}
              />
              <mesh
                name="SM_Env_Dirt_Rows_Skirt_26"
                castShadow
                receiveShadow
                geometry={nodes.SM_Env_Dirt_Rows_Skirt_26.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Env_Dirt_Rows_Skirt_26" }}
              />
              <mesh
                name="SM_Env_Dirt_Rows_Skirt_27"
                castShadow
                receiveShadow
                geometry={nodes.SM_Env_Dirt_Rows_Skirt_27.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Env_Dirt_Rows_Skirt_27" }}
              />
              <mesh
                name="SM_Env_Dirt_Rows_Skirt_28"
                castShadow
                receiveShadow
                geometry={nodes.SM_Env_Dirt_Rows_Skirt_28.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Env_Dirt_Rows_Skirt_28" }}
              />
            </group>
            <mesh
              name="SM_Prop_Scarecrow_02"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Scarecrow_02.geometry}
              material={materials.farm_pack}
              position={[-86.5262145996, 0, 0]}
              userData={{ name: "SM_Prop_Scarecrow_02" }}
            />
          </group>
          <group
            name="SM_Prop_Plant_Bush_03_Chilli14"
            userData={{ name: "SM_Prop_Plant_Bush_03_Chilli14" }}
          >
            <mesh
              name="Mesh503_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh503_1.geometry}
              material={materials.farm_pack}
            />
            <mesh
              name="Mesh503_2"
              castShadow
              receiveShadow
              geometry={nodes.Mesh503_2.geometry}
              material={materials.town_pack}
            />
            <mesh
              name="Mesh503_3"
              castShadow
              receiveShadow
              geometry={nodes.Mesh503_3.geometry}
              material={materials.farm_sign_mat}
            />
          </group>
        </group>
        <group
          name="longToolsShed_VERSIONS"
          userData={{ name: "longToolsShed_VERSIONS" }}
        >
          <group
            name="longToolsShed_v002"
            userData={{ name: "longToolsShed_v002" }}
          >
            <group
              name="long_tools_shed_FARM_PACK1"
              userData={{ name: "long_tools_shed_FARM_PACK1" }}
            >
              <mesh
                name="SM_Prop_Tool_Hoe_02001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_Tool_Hoe_02001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_Tool_Hoe_02.001" }}
              />
              <mesh
                name="SM_Prop_Tool_Pitchfork_02001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_Tool_Pitchfork_02001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_Tool_Pitchfork_02.001" }}
              />
              <mesh
                name="SM_Prop_Tool_Rake_02001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_Tool_Rake_02001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_Tool_Rake_02.001" }}
              />
              <mesh
                name="SM_Prop_Tool_Spade_02001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_Tool_Spade_02001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_Tool_Spade_02.001" }}
              />
            </group>
            <mesh
              name="polySurface546"
              castShadow
              receiveShadow
              geometry={nodes.polySurface546.geometry}
              material={materials.shops_pack}
              userData={{ name: "polySurface546" }}
            />
          </group>
          <group
            name="long_tools_shed_FARM_PACK"
            userData={{ name: "long_tools_shed_FARM_PACK" }}
          >
            <mesh
              name="SM_Bld_ProduceStand_04"
              castShadow
              receiveShadow
              geometry={nodes.SM_Bld_ProduceStand_04.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Bld_ProduceStand_04" }}
            />
            <mesh
              name="SM_Prop_Tool_Hoe_02"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Tool_Hoe_02.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Tool_Hoe_02" }}
            />
            <mesh
              name="SM_Prop_Tool_Pitchfork_02"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Tool_Pitchfork_02.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Tool_Pitchfork_02" }}
            />
            <mesh
              name="SM_Prop_Tool_Rake_02"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Tool_Rake_02.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Tool_Rake_02" }}
            />
            <mesh
              name="SM_Prop_Tool_Spade_02"
              castShadow
              receiveShadow
              geometry={nodes.SM_Prop_Tool_Spade_02.geometry}
              material={materials.farm_pack}
              userData={{ name: "SM_Prop_Tool_Spade_02" }}
            />
          </group>
          <group
            name="tool_small_shed_TOWN_PACK"
            userData={{ name: "tool_small_shed_TOWN_PACK" }}
          >
            <mesh
              name="polySurface42"
              castShadow
              receiveShadow
              geometry={nodes.polySurface42.geometry}
              material={materials.town_pack}
              userData={{ name: "polySurface42" }}
            />
            <mesh
              name="polySurface45"
              castShadow
              receiveShadow
              geometry={nodes.polySurface45.geometry}
              material={materials.town_pack}
              userData={{ name: "polySurface45" }}
            />
          </group>
          <mesh
            name="tool_shed_rack_SHOPS_PACK"
            castShadow
            receiveShadow
            geometry={nodes.tool_shed_rack_SHOPS_PACK.geometry}
            material={materials.shops_pack}
            userData={{ name: "tool_shed_rack_SHOPS_PACK" }}
          />
          <mesh
            name="SM_Prop_Tool_Hoe_02002"
            castShadow
            receiveShadow
            geometry={nodes.SM_Prop_Tool_Hoe_02002.geometry}
            material={materials.farm_pack}
            userData={{ name: "SM_Prop_Tool_Hoe_02.002" }}
          />
          <mesh
            name="SM_Prop_Tool_Pitchfork_02002"
            castShadow
            receiveShadow
            geometry={nodes.SM_Prop_Tool_Pitchfork_02002.geometry}
            material={materials.farm_pack}
            userData={{ name: "SM_Prop_Tool_Pitchfork_02.002" }}
          />
          <mesh
            name="SM_Prop_Tool_Rake_02002"
            castShadow
            receiveShadow
            geometry={nodes.SM_Prop_Tool_Rake_02002.geometry}
            material={materials.farm_pack}
            userData={{ name: "SM_Prop_Tool_Rake_02.002" }}
          />
          <mesh
            name="SM_Prop_Tool_Spade_02002"
            castShadow
            receiveShadow
            geometry={nodes.SM_Prop_Tool_Spade_02002.geometry}
            material={materials.farm_pack}
            userData={{ name: "SM_Prop_Tool_Spade_02.002" }}
          />
        </group>
        <group
          name="tool_shelf_VERSIONS"
          userData={{ name: "tool_shelf_VERSIONS" }}
        >
          <group name="tool_shelf_v001" userData={{ name: "tool_shelf_v001" }}>
            <group
              name="tools_FARM_PACK_v001"
              userData={{ name: "tools_FARM_PACK_v001" }}
            >
              <group name="group69" userData={{ name: "group69" }}>
                <mesh
                  name="SM_Prop_Tool_Axe_02"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_Tool_Axe_02.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_Tool_Axe_02" }}
                />
                <mesh
                  name="SM_Prop_Tool_Bucket_02"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_Tool_Bucket_02.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_Tool_Bucket_02" }}
                />
                <mesh
                  name="SM_Prop_ToolBox_03"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_ToolBox_03.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_ToolBox_03" }}
                />
              </group>
              <group name="seed_packets" userData={{ name: "seed_packets" }}>
                <mesh
                  name="SM_Prop_SeedPacket_03"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_SeedPacket_03.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_SeedPacket_03" }}
                />
                <mesh
                  name="SM_Prop_SeedPacket_04"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_SeedPacket_04.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_SeedPacket_04" }}
                />
                <mesh
                  name="SM_Prop_SeedPacket_05"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_SeedPacket_05.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_SeedPacket_05" }}
                />
                <mesh
                  name="SM_Prop_SeedPacket_06"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_SeedPacket_06.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_SeedPacket_06" }}
                />
                <mesh
                  name="SM_Prop_SeedPacket_07"
                  castShadow
                  receiveShadow
                  geometry={nodes.SM_Prop_SeedPacket_07.geometry}
                  material={materials.farm_pack}
                  userData={{ name: "SM_Prop_SeedPacket_07" }}
                />
              </group>
              <mesh
                name="tool_shed_table"
                castShadow
                receiveShadow
                geometry={nodes.tool_shed_table.geometry}
                material={materials.farm_pack}
                userData={{ name: "tool_shed_table" }}
              />
            </group>
            <group
              name="tools_TOWN_PACK_v001"
              userData={{ name: "tools_TOWN_PACK_v001" }}
            >
              <mesh
                name="Mesh482"
                castShadow
                receiveShadow
                geometry={nodes.Mesh482.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh482" }}
              />
              <mesh
                name="Mesh483"
                castShadow
                receiveShadow
                geometry={nodes.Mesh483.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh483" }}
              />
              <mesh
                name="Mesh484"
                castShadow
                receiveShadow
                geometry={nodes.Mesh484.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh484" }}
              />
              <mesh
                name="Mesh486"
                castShadow
                receiveShadow
                geometry={nodes.Mesh486.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh486" }}
              />
              <mesh
                name="Mesh695"
                castShadow
                receiveShadow
                geometry={nodes.Mesh695.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh695" }}
              />
              <mesh
                name="Mesh696"
                castShadow
                receiveShadow
                geometry={nodes.Mesh696.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh696" }}
              />
              <mesh
                name="tools_TOWN_PACK_v001_Mesh485"
                castShadow
                receiveShadow
                geometry={nodes.tools_TOWN_PACK_v001_Mesh485.geometry}
                material={materials.town_pack}
                userData={{ name: "tools_TOWN_PACK_v001_Mesh485" }}
              />
            </group>
          </group>
          <group name="tool_shelf" userData={{ name: "tool_shelf" }}>
            <mesh
              name="pCylinder26"
              castShadow
              receiveShadow
              geometry={nodes.pCylinder26.geometry}
              material={materials.lambert1}
              userData={{ name: "pCylinder26" }}
            />
            <mesh
              name="polySurface56"
              castShadow
              receiveShadow
              geometry={nodes.polySurface56.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface56" }}
            />
            <mesh
              name="polySurface59"
              castShadow
              receiveShadow
              geometry={nodes.polySurface59.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface59" }}
            />
            <mesh
              name="polySurface61"
              castShadow
              receiveShadow
              geometry={nodes.polySurface61.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface61" }}
            />
            <mesh
              name="polySurface62"
              castShadow
              receiveShadow
              geometry={nodes.polySurface62.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface62" }}
            />
            <mesh
              name="polySurface63"
              castShadow
              receiveShadow
              geometry={nodes.polySurface63.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface63" }}
            />
            <mesh
              name="polySurface64"
              castShadow
              receiveShadow
              geometry={nodes.polySurface64.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface64" }}
            />
            <mesh
              name="polySurface65"
              castShadow
              receiveShadow
              geometry={nodes.polySurface65.geometry}
              material={materials.farm_pack}
              userData={{ name: "polySurface65" }}
            />
          </group>
          <group
            name="tools_FARM_PACK_v002"
            userData={{ name: "tools_FARM_PACK_v002" }}
          >
            <group name="group70" userData={{ name: "group70" }}>
              <mesh
                name="SM_Prop_Tool_Axe_02001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_Tool_Axe_02001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_Tool_Axe_02.001" }}
              />
              <mesh
                name="SM_Prop_Tool_Bucket_02001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_Tool_Bucket_02001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_Tool_Bucket_02.001" }}
              />
              <mesh
                name="SM_Prop_ToolBox_03001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_ToolBox_03001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_ToolBox_03.001" }}
              />
            </group>
            <group name="seed_packets1" userData={{ name: "seed_packets1" }}>
              <mesh
                name="SM_Prop_SeedPacket_03001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_SeedPacket_03001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_SeedPacket_03.001" }}
              />
              <mesh
                name="SM_Prop_SeedPacket_04001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_SeedPacket_04001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_SeedPacket_04.001" }}
              />
              <mesh
                name="SM_Prop_SeedPacket_05001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_SeedPacket_05001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_SeedPacket_05.001" }}
              />
              <mesh
                name="SM_Prop_SeedPacket_06001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_SeedPacket_06001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_SeedPacket_06.001" }}
              />
              <mesh
                name="SM_Prop_SeedPacket_07001"
                castShadow
                receiveShadow
                geometry={nodes.SM_Prop_SeedPacket_07001.geometry}
                material={materials.farm_pack}
                userData={{ name: "SM_Prop_SeedPacket_07.001" }}
              />
            </group>
          </group>
          <group
            name="tools_TOWN_PACK_v002"
            userData={{ name: "tools_TOWN_PACK_v002" }}
          >
            <mesh
              name="Mesh482001"
              castShadow
              receiveShadow
              geometry={nodes.Mesh482001.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh482.001" }}
            />
            <mesh
              name="Mesh483001"
              castShadow
              receiveShadow
              geometry={nodes.Mesh483001.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh483.001" }}
            />
            <mesh
              name="Mesh484001"
              castShadow
              receiveShadow
              geometry={nodes.Mesh484001.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh484.001" }}
            />
            <mesh
              name="Mesh485"
              castShadow
              receiveShadow
              geometry={nodes.Mesh485.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh485" }}
            />
            <mesh
              name="Mesh486001"
              castShadow
              receiveShadow
              geometry={nodes.Mesh486001.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh486.001" }}
            />
            <mesh
              name="Mesh695001"
              castShadow
              receiveShadow
              geometry={nodes.Mesh695001.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh695.001" }}
            />
            <mesh
              name="Mesh696001"
              castShadow
              receiveShadow
              geometry={nodes.Mesh696001.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh696.001" }}
            />
          </group>
        </group>
        <group name="townPack" userData={{ name: "townPack" }}>
          <group
            name="garden_plants_sign"
            userData={{ name: "garden_plants_sign" }}
          >
            <mesh
              name="Mesh710"
              castShadow
              receiveShadow
              geometry={nodes.Mesh710.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh710" }}
            />
            <mesh
              name="Mesh711"
              castShadow
              receiveShadow
              geometry={nodes.Mesh711.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh711" }}
            />
            <mesh
              name="Mesh712"
              castShadow
              receiveShadow
              geometry={nodes.Mesh712.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh712" }}
            />
            <mesh
              name="Mesh713"
              castShadow
              receiveShadow
              geometry={nodes.Mesh713.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh713" }}
            />
            <mesh
              name="Mesh714"
              castShadow
              receiveShadow
              geometry={nodes.Mesh714.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh714" }}
            />
            <mesh
              name="Mesh715"
              castShadow
              receiveShadow
              geometry={nodes.Mesh715.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh715" }}
            />
            <mesh
              name="Mesh716"
              castShadow
              receiveShadow
              geometry={nodes.Mesh716.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh716" }}
            />
            <mesh
              name="Mesh717"
              castShadow
              receiveShadow
              geometry={nodes.Mesh717.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh717" }}
            />
            <mesh
              name="Mesh718"
              castShadow
              receiveShadow
              geometry={nodes.Mesh718.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh718" }}
            />
            <mesh
              name="Mesh719"
              castShadow
              receiveShadow
              geometry={nodes.Mesh719.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh719" }}
            />
            <mesh
              name="Mesh720"
              castShadow
              receiveShadow
              geometry={nodes.Mesh720.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh720" }}
            />
          </group>
          <group
            name="small_rock_and_grass"
            userData={{ name: "small_rock_and_grass" }}
          >
            <group name="grass" userData={{ name: "grass" }}>
              <mesh
                name="Mesh375"
                castShadow
                receiveShadow
                geometry={nodes.Mesh375.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh375" }}
              />
              <mesh
                name="Mesh376"
                castShadow
                receiveShadow
                geometry={nodes.Mesh376.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh376" }}
              />
              <mesh
                name="Mesh377"
                castShadow
                receiveShadow
                geometry={nodes.Mesh377.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh377" }}
              />
              <mesh
                name="Mesh678"
                castShadow
                receiveShadow
                geometry={nodes.Mesh678.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh678" }}
              />
              <mesh
                name="Mesh679"
                castShadow
                receiveShadow
                geometry={nodes.Mesh679.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh679" }}
              />
              <mesh
                name="Mesh680"
                castShadow
                receiveShadow
                geometry={nodes.Mesh680.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh680" }}
              />
              <mesh
                name="Mesh681"
                castShadow
                receiveShadow
                geometry={nodes.Mesh681.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh681" }}
              />
              <mesh
                name="Mesh682"
                castShadow
                receiveShadow
                geometry={nodes.Mesh682.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh682" }}
              />
              <mesh
                name="Mesh683"
                castShadow
                receiveShadow
                geometry={nodes.Mesh683.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh683" }}
              />
              <mesh
                name="Mesh684"
                castShadow
                receiveShadow
                geometry={nodes.Mesh684.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh684" }}
              />
              <mesh
                name="Mesh685"
                castShadow
                receiveShadow
                geometry={nodes.Mesh685.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh685" }}
              />
              <mesh
                name="Mesh698"
                castShadow
                receiveShadow
                geometry={nodes.Mesh698.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh698" }}
              />
              <mesh
                name="Mesh699"
                castShadow
                receiveShadow
                geometry={nodes.Mesh699.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh699" }}
              />
              <mesh
                name="Mesh700"
                castShadow
                receiveShadow
                geometry={nodes.Mesh700.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh700" }}
              />
              <mesh
                name="Mesh702"
                castShadow
                receiveShadow
                geometry={nodes.Mesh702.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh702" }}
              />
              <mesh
                name="Mesh703"
                castShadow
                receiveShadow
                geometry={nodes.Mesh703.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh703" }}
              />
              <mesh
                name="Mesh704"
                castShadow
                receiveShadow
                geometry={nodes.Mesh704.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh704" }}
              />
              <mesh
                name="Mesh705"
                castShadow
                receiveShadow
                geometry={nodes.Mesh705.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh705" }}
              />
              <mesh
                name="Mesh706"
                castShadow
                receiveShadow
                geometry={nodes.Mesh706.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh706" }}
              />
              <mesh
                name="Mesh707"
                castShadow
                receiveShadow
                geometry={nodes.Mesh707.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh707" }}
              />
              <mesh
                name="Mesh708"
                castShadow
                receiveShadow
                geometry={nodes.Mesh708.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh708" }}
              />
              <mesh
                name="Mesh709"
                castShadow
                receiveShadow
                geometry={nodes.Mesh709.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh709" }}
              />
            </group>
            <group name="rock" userData={{ name: "rock" }}>
              <mesh
                name="Mesh492"
                castShadow
                receiveShadow
                geometry={nodes.Mesh492.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh492" }}
              />
              <mesh
                name="Mesh493"
                castShadow
                receiveShadow
                geometry={nodes.Mesh493.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh493" }}
              />
              <mesh
                name="Mesh494"
                castShadow
                receiveShadow
                geometry={nodes.Mesh494.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh494" }}
              />
              <mesh
                name="Mesh495"
                castShadow
                receiveShadow
                geometry={nodes.Mesh495.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh495" }}
              />
              <mesh
                name="Mesh496"
                castShadow
                receiveShadow
                geometry={nodes.Mesh496.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh496" }}
              />
              <mesh
                name="Mesh497"
                castShadow
                receiveShadow
                geometry={nodes.Mesh497.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh497" }}
              />
              <mesh
                name="Mesh498"
                castShadow
                receiveShadow
                geometry={nodes.Mesh498.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh498" }}
              />
              <mesh
                name="Mesh499"
                castShadow
                receiveShadow
                geometry={nodes.Mesh499.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh499" }}
              />
              <mesh
                name="Mesh500"
                castShadow
                receiveShadow
                geometry={nodes.Mesh500.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh500" }}
              />
              <mesh
                name="Mesh501"
                castShadow
                receiveShadow
                geometry={nodes.Mesh501.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh501" }}
              />
              <mesh
                name="Mesh502"
                castShadow
                receiveShadow
                geometry={nodes.Mesh502.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh502" }}
              />
              <mesh
                name="Mesh503"
                castShadow
                receiveShadow
                geometry={nodes.Mesh503.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh503" }}
              />
              <mesh
                name="Mesh504"
                castShadow
                receiveShadow
                geometry={nodes.Mesh504.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh504" }}
              />
              <mesh
                name="Mesh505"
                castShadow
                receiveShadow
                geometry={nodes.Mesh505.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh505" }}
              />
              <mesh
                name="Mesh506"
                castShadow
                receiveShadow
                geometry={nodes.Mesh506.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh506" }}
              />
              <mesh
                name="Mesh507"
                castShadow
                receiveShadow
                geometry={nodes.Mesh507.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh507" }}
              />
              <mesh
                name="Mesh508"
                castShadow
                receiveShadow
                geometry={nodes.Mesh508.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh508" }}
              />
              <mesh
                name="Mesh509"
                castShadow
                receiveShadow
                geometry={nodes.Mesh509.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh509" }}
              />
              <mesh
                name="Mesh510"
                castShadow
                receiveShadow
                geometry={nodes.Mesh510.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh510" }}
              />
              <mesh
                name="Mesh511"
                castShadow
                receiveShadow
                geometry={nodes.Mesh511.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh511" }}
              />
              <mesh
                name="Mesh512"
                castShadow
                receiveShadow
                geometry={nodes.Mesh512.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh512" }}
              />
              <mesh
                name="Mesh513"
                castShadow
                receiveShadow
                geometry={nodes.Mesh513.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh513" }}
              />
              <mesh
                name="Mesh514"
                castShadow
                receiveShadow
                geometry={nodes.Mesh514.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh514" }}
              />
              <mesh
                name="Mesh515"
                castShadow
                receiveShadow
                geometry={nodes.Mesh515.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh515" }}
              />
              <mesh
                name="Mesh516"
                castShadow
                receiveShadow
                geometry={nodes.Mesh516.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh516" }}
              />
              <mesh
                name="Mesh517"
                castShadow
                receiveShadow
                geometry={nodes.Mesh517.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh517" }}
              />
              <mesh
                name="Mesh518"
                castShadow
                receiveShadow
                geometry={nodes.Mesh518.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh518" }}
              />
              <mesh
                name="Mesh519"
                castShadow
                receiveShadow
                geometry={nodes.Mesh519.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh519" }}
              />
              <mesh
                name="Mesh520"
                castShadow
                receiveShadow
                geometry={nodes.Mesh520.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh520" }}
              />
              <mesh
                name="Mesh521"
                castShadow
                receiveShadow
                geometry={nodes.Mesh521.geometry}
                material={materials.town_pack}
                userData={{ name: "Mesh521" }}
              />
            </group>
          </group>
          <group name="tool_shed_misc" userData={{ name: "tool_shed_misc" }}>
            <mesh
              name="Mesh475"
              castShadow
              receiveShadow
              geometry={nodes.Mesh475.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh475" }}
            />
            <mesh
              name="Mesh477"
              castShadow
              receiveShadow
              geometry={nodes.Mesh477.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh477" }}
            />
            <mesh
              name="Mesh487"
              castShadow
              receiveShadow
              geometry={nodes.Mesh487.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh487" }}
            />
          </group>
          <group
            name="watering_hoes_can"
            userData={{ name: "watering_hoes_can" }}
          >
            <mesh
              name="Mesh488"
              castShadow
              receiveShadow
              geometry={nodes.Mesh488.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh488" }}
            />
            <mesh
              name="Mesh489"
              castShadow
              receiveShadow
              geometry={nodes.Mesh489.geometry}
              material={materials.town_pack}
              userData={{ name: "Mesh489" }}
            />
          </group>
          <mesh
            name="ground"
            castShadow
            receiveShadow
            geometry={nodes.ground.geometry}
            material={materials.town_pack}
            userData={{ name: "ground" }}
          />
          <mesh
            name="flower_box"
            castShadow
            receiveShadow
            geometry={nodes.flower_box.geometry}
            material={materials.town_pack}
            userData={{ name: "flower_box" }}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/game_assets/models/Garden_Test-transformed.glb");

export default memo(Garden);
