/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 Kitchen_v002.glb --transform --precision=10 --shadows --keepnames --meta --types
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { memo, MutableRefObject, useRef } from "react";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    main_table105: THREE.Mesh;
    main_table233: THREE.Mesh;
    main_table234: THREE.Mesh;
    main_table254: THREE.Mesh;
    main_table229: THREE.Mesh;
    main_table253: THREE.Mesh;
    main_table259: THREE.Mesh;
    main_table66: THREE.Mesh;
    main_table66003: THREE.Mesh;
    main_table136: THREE.Mesh;
    main_table176: THREE.Mesh;
    main_table230: THREE.Mesh;
    main_table231: THREE.Mesh;
    main_table232: THREE.Mesh;
    main_table238: THREE.Mesh;
    main_table239: THREE.Mesh;
    main_table258: THREE.Mesh;
    main_table96: THREE.Mesh;
    comb_selves2_main_table160001: THREE.Mesh;
    comb_selves2_main_table160002: THREE.Mesh;
    comb_selves2_main_table160003: THREE.Mesh;
    comb_selves2_main_table160004: THREE.Mesh;
    comb_selves2_main_table160005: THREE.Mesh;
    Mesh002: THREE.Mesh;
    Mesh002_1: THREE.Mesh;
    Mesh002_2: THREE.Mesh;
    Mesh002_3: THREE.Mesh;
    polySurface185: THREE.Mesh;
    polySurface185001: THREE.Mesh;
    polySurface185002: THREE.Mesh;
    polySurface185003: THREE.Mesh;
    polySurface185004: THREE.Mesh;
    polySurface255001: THREE.Mesh;
    polySurface258001: THREE.Mesh;
    polySurface326: THREE.Mesh;
    polySurface327: THREE.Mesh;
    polySurface378: THREE.Mesh;
    polySurface378001: THREE.Mesh;
    room_BASE_no_backside_comb_window: THREE.Mesh;
    room_BASE_no_backside_comb_window001: THREE.Mesh;
    polySurface2687001: THREE.Mesh;
    Mesh292: THREE.Mesh;
    Mesh292_1: THREE.Mesh;
    Mesh287: THREE.Mesh;
    Mesh287_1: THREE.Mesh;
    Mesh290: THREE.Mesh;
    Mesh290_1: THREE.Mesh;
    Mesh291: THREE.Mesh;
    Mesh291_1: THREE.Mesh;
    polySurface761: THREE.Mesh;
    polySurface773: THREE.Mesh;
    Mesh590: THREE.Mesh;
    Mesh590_1: THREE.Mesh;
    Mesh590_2: THREE.Mesh;
    Mesh304: THREE.Mesh;
    Mesh304_1: THREE.Mesh;
    Mesh304_2: THREE.Mesh;
    Mesh304_3: THREE.Mesh;
    Mesh595: THREE.Mesh;
    Mesh595_1: THREE.Mesh;
    Mesh595_2: THREE.Mesh;
    Mesh350: THREE.Mesh;
    Mesh350_1: THREE.Mesh;
    Mesh350_2: THREE.Mesh;
    Mesh350_3: THREE.Mesh;
    polySurface922: THREE.Mesh;
    Mesh600: THREE.Mesh;
    Mesh600_1: THREE.Mesh;
    Mesh600_2: THREE.Mesh;
    Mesh600_3: THREE.Mesh;
    Mesh600_4: THREE.Mesh;
    Mesh599: THREE.Mesh;
    Mesh599_1: THREE.Mesh;
    Mesh599_2: THREE.Mesh;
    Mesh365: THREE.Mesh;
    Mesh365_1: THREE.Mesh;
    Mesh365_2: THREE.Mesh;
    Mesh365_3: THREE.Mesh;
    Mesh366: THREE.Mesh;
    Mesh366_1: THREE.Mesh;
    polySurface975: THREE.Mesh;
    polySurface975001: THREE.Mesh;
    Mesh429: THREE.Mesh;
    Mesh429_1: THREE.Mesh;
    Mesh429_2: THREE.Mesh;
    polySurface1835: THREE.Mesh;
    polySurface1836: THREE.Mesh;
    polySurface1837: THREE.Mesh;
    polySurface1838: THREE.Mesh;
    polySurface1841: THREE.Mesh;
    polySurface1842: THREE.Mesh;
    polySurface1844: THREE.Mesh;
    polySurface1845: THREE.Mesh;
    polySurface1865: THREE.Mesh;
    polySurface1866: THREE.Mesh;
    polySurface1867: THREE.Mesh;
    polySurface2727: THREE.Mesh;
    polySurface2728: THREE.Mesh;
    polySurface2729: THREE.Mesh;
    Mesh597: THREE.Mesh;
    Mesh597_1: THREE.Mesh;
    polySurface2702: THREE.Mesh;
    polySurface2720: THREE.Mesh;
    Mesh542: THREE.Mesh;
    Mesh542_1: THREE.Mesh;
    Mesh541: THREE.Mesh;
    Mesh541_1: THREE.Mesh;
    ground: THREE.Mesh;
    Cube: THREE.Mesh;
  };
  materials: {
    TilesYellow: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    Brown: THREE.MeshStandardMaterial;
    Green: THREE.MeshStandardMaterial;
    Yellow: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
    Beige: THREE.MeshStandardMaterial;
    Orange: THREE.MeshStandardMaterial;
    WallsYellow: THREE.MeshStandardMaterial;
    Dark: THREE.MeshStandardMaterial;
    Teal: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    Blue: THREE.MeshStandardMaterial;
    Green02: THREE.MeshStandardMaterial;
    Purple: THREE.MeshStandardMaterial;
    Floors: THREE.MeshStandardMaterial;
  };
};

const Kitchen = (props: JSX.IntrinsicElements["group"]) => {
  const pieRef: MutableRefObject<THREE.Group | null> = useRef(null);
  const { nodes, materials } = useGLTF(
    "/game_assets/models/Kitchen_v002-transformed.glb"
  ) as GLTFResult;

  useFrame(({ clock }) => {
    if (pieRef.current) {
      // pieRef.current.position.z = THREE.MathUtils.mapLinear(
      //   Math.sin(clock.getElapsedTime()),
      //   -1,
      //   1,
      //   -20,
      //   0
      // );
      // pieRef.current.position.x = THREE.MathUtils.mapLinear(
      //   Math.cos(clock.getElapsedTime()),
      //   -1,
      //   1,
      //   -20,
      //   0
      // );
      // pieRef.current.position.y = THREE.MathUtils.mapLinear(
      //   Math.cos(clock.getElapsedTime()),
      //   -1,
      //   1,
      //   20,
      //   0
      // );
    }
  });

  return (
    <group {...props} dispose={null}>
      <group
        name="town_items"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0099999998}
        userData={{ name: "town_items" }}
      >
        <mesh
          name="polySurface2687001"
          castShadow
          receiveShadow
          geometry={nodes.polySurface2687001.geometry}
          material={nodes.polySurface2687001.material}
          position={[322.5776977539, -54.7548904419, -96.8162841797]}
          rotation={[0, 0, -Math.PI / 2]}
          userData={{ name: "polySurface2687.001" }}
        />
        <group
          name="polySurface602"
          position={[374.0935668945, -210.0645141602, -199.3416900635]}
          userData={{ name: "polySurface602" }}
        >
          <mesh
            name="Mesh292"
            castShadow
            receiveShadow
            geometry={nodes.Mesh292.geometry}
            material={materials.Green}
          />
          <mesh
            name="Mesh292_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh292_1.geometry}
            material={materials.Beige}
          />
        </group>
        <group
          name="polySurface621"
          position={[364.966583252, -23.2712974548, -115.371131897]}
          rotation={[0, 0, 0.7979069058]}
          userData={{ name: "polySurface621" }}
        >
          <mesh
            name="Mesh287"
            castShadow
            receiveShadow
            geometry={nodes.Mesh287.geometry}
            material={materials.Red}
          />
          <mesh
            name="Mesh287_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh287_1.geometry}
            material={materials.Green}
          />
        </group>
        <group
          name="polySurface640"
          position={[367.5997619629, -33.0823898315, -208.8793029785]}
          rotation={[0, 0, -0.7382742706]}
          userData={{ name: "polySurface640" }}
        >
          <mesh
            name="Mesh290"
            castShadow
            receiveShadow
            geometry={nodes.Mesh290.geometry}
            material={materials.Green}
          />
          <mesh
            name="Mesh290_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh290_1.geometry}
            material={materials.Red}
          />
        </group>
        <group
          name="polySurface698"
          position={[377.6899414063, -298.6190185547, -182.5999450684]}
          rotation={[0, 0, -0.6667157918]}
          userData={{ name: "polySurface698" }}
        >
          <mesh
            name="Mesh291"
            castShadow
            receiveShadow
            geometry={nodes.Mesh291.geometry}
            material={materials.Green}
          />
          <mesh
            name="Mesh291_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh291_1.geometry}
            material={materials.Red}
          />
        </group>
        <mesh
          name="polySurface761"
          castShadow
          receiveShadow
          geometry={nodes.polySurface761.geometry}
          material={materials.Orange}
          position={[197.306350708, -315.2813720703, -61.5679359436]}
          userData={{ name: "polySurface761" }}
        />
        <mesh
          name="polySurface773"
          castShadow
          receiveShadow
          geometry={nodes.polySurface773.geometry}
          material={materials.Dark}
          position={[244.3319396973, -159.4134979248, -2.2853672504]}
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: "polySurface773" }}
        />
        <group
          name="polySurface777001"
          position={[393.3623046875, -115.014503479, -179.1889343262]}
          userData={{ name: "polySurface777.001" }}
        >
          <mesh
            name="Mesh590"
            castShadow
            receiveShadow
            geometry={nodes.Mesh590.geometry}
            material={materials.Red}
          />
          <mesh
            name="Mesh590_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh590_1.geometry}
            material={materials.Green}
          />
          <mesh
            name="Mesh590_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh590_2.geometry}
            material={materials.White}
          />
        </group>
        <group
          name="polySurface784"
          position={[375.7150268555, -278.4664306641, -183.0244445801]}
          userData={{ name: "polySurface784" }}
        >
          <mesh
            name="Mesh304"
            castShadow
            receiveShadow
            geometry={nodes.Mesh304.geometry}
            material={materials.Green}
          />
          <mesh
            name="Mesh304_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh304_1.geometry}
            material={materials.Red}
          />
          <mesh
            name="Mesh304_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh304_2.geometry}
            material={materials.White}
          />
          <mesh
            name="Mesh304_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh304_3.geometry}
            material={materials.Yellow}
          />
        </group>
        <group
          name="polySurface864001"
          position={[362.6446228027, -302.9936218262, -110.090713501]}
          rotation={[0, 0, Math.PI / 2]}
          userData={{ name: "polySurface864.001" }}
        >
          <mesh
            name="Mesh595"
            castShadow
            receiveShadow
            geometry={nodes.Mesh595.geometry}
            material={materials.Yellow}
          />
          <mesh
            name="Mesh595_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh595_1.geometry}
            material={materials.White}
          />
          <mesh
            name="Mesh595_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh595_2.geometry}
            material={materials.Red}
          />
        </group>
        <group
          name="polySurface906"
          position={[321.6984863281, -240.1894989014, -52.1863136292]}
          userData={{ name: "polySurface906" }}
        >
          <mesh
            name="Mesh350"
            castShadow
            receiveShadow
            geometry={nodes.Mesh350.geometry}
            material={materials.Orange}
          />
          <mesh
            name="Mesh350_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh350_1.geometry}
            material={materials.Teal}
          />
          <mesh
            name="Mesh350_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh350_2.geometry}
            material={materials.Metal}
          />
          <mesh
            name="Mesh350_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh350_3.geometry}
            material={materials.Dark}
          />
        </group>
        <mesh
          name="polySurface922"
          castShadow
          receiveShadow
          geometry={nodes.polySurface922.geometry}
          material={materials.Metal}
          position={[371.0466003418, -112.7444152832, -121.3580093384]}
          userData={{ name: "polySurface922" }}
        />
        <group
          name="polySurface938001"
          position={[365.0774841309, -279.465057373, -111.8777770996]}
          rotation={[0, 0, -Math.PI / 2]}
          userData={{ name: "polySurface938.001" }}
        >
          <mesh
            name="Mesh600"
            castShadow
            receiveShadow
            geometry={nodes.Mesh600.geometry}
            material={materials.White}
          />
          <mesh
            name="Mesh600_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh600_1.geometry}
            material={materials.Red}
          />
          <mesh
            name="Mesh600_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh600_2.geometry}
            material={materials.Blue}
          />
          <mesh
            name="Mesh600_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh600_3.geometry}
            material={materials.Yellow}
          />
          <mesh
            name="Mesh600_4"
            castShadow
            receiveShadow
            geometry={nodes.Mesh600_4.geometry}
            material={materials.Beige}
          />
        </group>
        <group
          name="polySurface955001"
          position={[320.2418212891, -303.6759033203, -106.5676803589]}
          userData={{ name: "polySurface955.001" }}
        >
          <mesh
            name="Mesh599"
            castShadow
            receiveShadow
            geometry={nodes.Mesh599.geometry}
            material={materials.Green02}
          />
          <mesh
            name="Mesh599_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh599_1.geometry}
            material={materials.Red}
          />
          <mesh
            name="Mesh599_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh599_2.geometry}
            material={materials.Brown}
          />
        </group>
        <group
          name="polySurface962"
          position={[364.8641967773, -82.8659973145, -121.2625350952]}
          userData={{ name: "polySurface962" }}
        >
          <mesh
            name="Mesh365"
            castShadow
            receiveShadow
            geometry={nodes.Mesh365.geometry}
            material={materials.Red}
          />
          <mesh
            name="Mesh365_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh365_1.geometry}
            material={materials.Brown}
          />
          <mesh
            name="Mesh365_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh365_2.geometry}
            material={materials.Metal}
          />
          <mesh
            name="Mesh365_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh365_3.geometry}
            material={materials.Dark}
          />
        </group>
        <group
          name="polySurface963"
          position={[357.763671875, -51.9478492737, -107.1026687622]}
          userData={{ name: "polySurface963" }}
        >
          <mesh
            name="Mesh366"
            castShadow
            receiveShadow
            geometry={nodes.Mesh366.geometry}
            material={materials.Metal}
          />
          <mesh
            name="Mesh366_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh366_1.geometry}
            material={materials.Dark}
          />
        </group>
        <mesh
          name="polySurface975"
          castShadow
          receiveShadow
          geometry={nodes.polySurface975.geometry}
          material={materials.Beige}
          position={[383.7459716797, -315.4187011719, -167.69480896]}
          userData={{ name: "polySurface975" }}
        />
        <mesh
          name="polySurface975001"
          castShadow
          receiveShadow
          geometry={nodes.polySurface975001.geometry}
          material={materials.Beige}
          position={[383.7459716797, -323.8360595703, -170.7377929688]}
          scale={[1, 1, 1.3965505362]}
          userData={{ name: "polySurface975.001" }}
        />
      </group>
      <group
        name="shops_items"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0099999998}
        userData={{ name: "shops_items" }}
      >
        <group
          name="polySurface1822"
          position={[365.827331543, -231.1301879883, -125.1708145142]}
          scale={1.0572021008}
          userData={{ name: "polySurface1822" }}
        >
          <mesh
            name="Mesh429"
            castShadow
            receiveShadow
            geometry={nodes.Mesh429.geometry}
            material={materials.Dark}
          />
          <mesh
            name="Mesh429_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh429_1.geometry}
            material={materials.Metal}
          />
          <mesh
            name="Mesh429_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh429_2.geometry}
            material={materials.Red}
          />
        </group>
        <mesh
          name="polySurface1835"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1835.geometry}
          material={materials.Metal}
          position={[377.5928344727, -0.1226797104, -172.9164123535]}
          userData={{ name: "polySurface1835" }}
        />
        <mesh
          name="polySurface1836"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1836.geometry}
          material={materials.Metal}
          position={[378.7291870117, -10.5573186874, -176.195098877]}
          userData={{ name: "polySurface1836" }}
        />
        <mesh
          name="polySurface1837"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1837.geometry}
          material={materials.Metal}
          position={[378.7291259766, -46.8784561157, -173.8757781982]}
          userData={{ name: "polySurface1837" }}
        />
        <mesh
          name="polySurface1838"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1838.geometry}
          material={materials.Metal}
          position={[377.5927429199, -65.4749450684, -175.0219116211]}
          userData={{ name: "polySurface1838" }}
        />
        <mesh
          name="polySurface1841"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1841.geometry}
          material={materials.Metal}
          position={[371.4266052246, -261.3982543945, -170.9585266113]}
          userData={{ name: "polySurface1841" }}
        />
        <mesh
          name="polySurface1842"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1842.geometry}
          material={materials.Dark}
          position={[375.0618591309, -255.375793457, -170.9585113525]}
          userData={{ name: "polySurface1842" }}
        />
        <mesh
          name="polySurface1844"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1844.geometry}
          material={nodes.polySurface1844.material}
          position={[346.8416748047, -388.2714233398, -169.8830108643]}
          userData={{ name: "polySurface1844" }}
        />
        <mesh
          name="polySurface1845"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1845.geometry}
          material={nodes.polySurface1845.material}
          position={[337.9024963379, -388.2713012695, -172.343963623]}
          userData={{ name: "polySurface1845" }}
        />
        <mesh
          name="polySurface1865"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1865.geometry}
          material={materials.Blue}
          position={[361.1434020996, -53.1363830566, -166.1187896729]}
          userData={{ name: "polySurface1865" }}
        />
        <mesh
          name="polySurface1866"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1866.geometry}
          material={materials.Blue}
          position={[361.1434020996, -53.1363830566, -170.6870117188]}
          userData={{ name: "polySurface1866" }}
        />
        <mesh
          name="polySurface1867"
          castShadow
          receiveShadow
          geometry={nodes.polySurface1867.geometry}
          material={materials.Yellow}
          position={[361.1434020996, -53.1363830566, -175.2551727295]}
          userData={{ name: "polySurface1867" }}
        />
        <mesh
          name="polySurface2727"
          castShadow
          receiveShadow
          geometry={nodes.polySurface2727.geometry}
          material={materials.Beige}
          position={[342.2222595215, -264.2071228027, -96.2043075562]}
          userData={{ name: "polySurface2727" }}
        />
        <mesh
          name="polySurface2728"
          castShadow
          receiveShadow
          geometry={nodes.polySurface2728.geometry}
          material={materials.Beige}
          position={[335.6783752441, -16.2827587128, -96.2043075562]}
          userData={{ name: "polySurface2728" }}
        />
        <mesh
          name="polySurface2729"
          castShadow
          receiveShadow
          geometry={nodes.polySurface2729.geometry}
          material={materials.Beige}
          position={[325.7889404297, -232.9614105225, -96.4975967407]}
          scale={1.375180006}
          userData={{ name: "polySurface2729" }}
        />
      </group>
      <group
        name="FOOD_items_shop"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0099999998}
        userData={{ name: "FOOD_items_shop" }}
      >
        <group
          name="polySurface2693001"
          position={[323.9603881836, -75.8938903809, -101.6031723022]}
          rotation={[0, 0, 1.4294247735]}
          scale={0.851485312}
          userData={{ name: "polySurface2693.001" }}
        >
          <mesh
            name="Mesh597"
            castShadow
            receiveShadow
            geometry={nodes.Mesh597.geometry}
            material={materials.Red}
          />
          <mesh
            name="Mesh597_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh597_1.geometry}
            material={materials.Green}
          />
        </group>
        <mesh
          name="polySurface2702"
          castShadow
          receiveShadow
          geometry={nodes.polySurface2702.geometry}
          material={nodes.polySurface2702.material}
          position={[365.4110107422, -252.9979400635, -101.4263000488]}
          userData={{ name: "polySurface2702" }}
        />
        <mesh
          name="polySurface2720"
          castShadow
          receiveShadow
          geometry={nodes.polySurface2720.geometry}
          material={materials.Orange}
          position={[336.0258789063, -16.7515983582, -99.6755981445]}
          userData={{ name: "polySurface2720" }}
        />
        <group
          name="polySurface2721"
          position={[324.1200561523, -234.3034210205, -100.1600952148]}
          userData={{ name: "polySurface2721" }}
        >
          <group ref={pieRef}>
            <mesh
              name="Mesh542"
              castShadow
              receiveShadow
              geometry={nodes.Mesh542.geometry}
              material={materials.Orange}
            />
            <mesh
              name="Mesh542_1"
              castShadow
              receiveShadow
              geometry={nodes.Mesh542_1.geometry}
              material={materials.Red}
            />
          </group>
        </group>
        <group
          name="polySurface2722"
          position={[341.5459594727, -264.0152893066, -98.6206741333]}
          userData={{ name: "polySurface2722" }}
        >
          <mesh
            name="Mesh541"
            castShadow
            receiveShadow
            geometry={nodes.Mesh541.geometry}
            material={materials.Orange}
          />
          <mesh
            name="Mesh541_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh541_1.geometry}
            material={materials.Purple}
          />
        </group>
      </group>
      <mesh
        name="ground"
        castShadow
        receiveShadow
        geometry={nodes.ground.geometry}
        material={materials.Floors}
        position={[-0.3393776119, 0, -0.1696888059]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0099999998}
        userData={{ name: "ground" }}
      />
      <mesh
        name="Cube"
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.Orange}
        position={[3.98351717, 0.8534080982, -1.5706300735]}
        scale={[0.1184269786, 0.1184269786, 3.6384270191]}
        userData={{ name: "Cube" }}
      />
      <group
        name="proxy_all"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0099999998}
        userData={{ name: "proxy_all" }}
      >
        <group
          name="back_splash_color_2"
          userData={{ name: "back_splash_color_2" }}
        >
          <group name="group26" userData={{ name: "group26" }}>
            <mesh
              name="main_table105"
              castShadow
              receiveShadow
              geometry={nodes.main_table105.geometry}
              material={nodes.main_table105.material}
              position={[322.8499145508, -396.1321411133, -140.4417572021]}
              userData={{ name: "main_table105" }}
            />
            <mesh
              name="main_table233"
              castShadow
              receiveShadow
              geometry={nodes.main_table233.geometry}
              material={nodes.main_table233.material}
              position={[363.0755004883, -396.1321411133, -117.2175521851]}
              userData={{ name: "main_table233" }}
            />
            <mesh
              name="main_table234"
              castShadow
              receiveShadow
              geometry={nodes.main_table234.geometry}
              material={nodes.main_table234.material}
              position={[376.4839477539, -396.1321411133, -93.9933319092]}
              userData={{ name: "main_table234" }}
            />
            <mesh
              name="main_table254"
              castShadow
              receiveShadow
              geometry={nodes.main_table254.geometry}
              material={nodes.main_table254.material}
              position={[336.2585144043, -396.1321411133, -101.7347335815]}
              userData={{ name: "main_table254" }}
            />
          </group>
          <group name="group27" userData={{ name: "group27" }}>
            <mesh
              name="main_table229"
              castShadow
              receiveShadow
              geometry={nodes.main_table229.geometry}
              material={nodes.main_table229.material}
              position={[336.2585144043, -396.1321411133, -117.2175521851]}
              userData={{ name: "main_table229" }}
            />
            <mesh
              name="main_table253"
              castShadow
              receiveShadow
              geometry={nodes.main_table253.geometry}
              material={nodes.main_table253.material}
              position={[322.8499145508, -396.1321411133, -93.9933319092]}
              userData={{ name: "main_table253" }}
            />
            <mesh
              name="main_table259"
              castShadow
              receiveShadow
              geometry={nodes.main_table259.geometry}
              material={nodes.main_table259.material}
              position={[363.0755004883, -396.1321411133, -101.7347335815]}
              userData={{ name: "main_table259" }}
            />
            <mesh
              name="main_table66"
              castShadow
              receiveShadow
              geometry={nodes.main_table66.geometry}
              material={materials.TilesYellow}
              position={[388.3096923828, -116.4800109863, -109.4761428833]}
              userData={{ name: "main_table66" }}
            />
            <mesh
              name="main_table66003"
              castShadow
              receiveShadow
              geometry={nodes.main_table66003.geometry}
              material={materials.White}
              position={[376.3960266113, -130.3713684082, -96.9715805054]}
              userData={{ name: "main_table66.003" }}
            />
          </group>
          <group name="group28" userData={{ name: "group28" }}>
            <mesh
              name="main_table136"
              castShadow
              receiveShadow
              geometry={nodes.main_table136.geometry}
              material={materials.TilesYellow}
              position={[388.3096313477, -223.7481079102, -93.9933242798]}
              userData={{ name: "main_table136" }}
            />
            <mesh
              name="main_table176"
              castShadow
              receiveShadow
              geometry={nodes.main_table176.geometry}
              material={nodes.main_table176.material}
              position={[349.6669921875, -396.1284790039, -143.27684021]}
              userData={{ name: "main_table176" }}
            />
            <mesh
              name="main_table230"
              castShadow
              receiveShadow
              geometry={nodes.main_table230.geometry}
              material={nodes.main_table230.material}
              position={[349.6669921875, -396.1321411133, -124.9589691162]}
              userData={{ name: "main_table230" }}
            />
            <mesh
              name="main_table231"
              castShadow
              receiveShadow
              geometry={nodes.main_table231.geometry}
              material={nodes.main_table231.material}
              position={[349.6669921875, -396.1321411133, -109.4761505127]}
              userData={{ name: "main_table231" }}
            />
            <mesh
              name="main_table232"
              castShadow
              receiveShadow
              geometry={nodes.main_table232.geometry}
              material={nodes.main_table232.material}
              position={[322.8499145508, -396.1321411133, -109.4761505127]}
              userData={{ name: "main_table232" }}
            />
            <mesh
              name="main_table238"
              castShadow
              receiveShadow
              geometry={nodes.main_table238.geometry}
              material={nodes.main_table238.material}
              position={[376.4839477539, -396.1321411133, -109.4761505127]}
              userData={{ name: "main_table238" }}
            />
            <mesh
              name="main_table239"
              castShadow
              receiveShadow
              geometry={nodes.main_table239.geometry}
              material={nodes.main_table239.material}
              position={[377.2715454102, -396.1284790039, -127.8942947388]}
              userData={{ name: "main_table239" }}
            />
            <mesh
              name="main_table258"
              castShadow
              receiveShadow
              geometry={nodes.main_table258.geometry}
              material={nodes.main_table258.material}
              position={[349.6669921875, -396.1321411133, -93.9933319092]}
              userData={{ name: "main_table258" }}
            />
            <mesh
              name="main_table96"
              castShadow
              receiveShadow
              geometry={nodes.main_table96.geometry}
              material={nodes.main_table96.material}
              position={[322.8500366211, -396.1321411133, -124.9589691162]}
              userData={{ name: "main_table96" }}
            />
          </group>
        </group>
        <mesh
          name="comb_selves2_main_table160001"
          castShadow
          receiveShadow
          geometry={nodes.comb_selves2_main_table160001.geometry}
          material={materials.Brown}
          position={[378.7722473145, -69.1664428711, -217.3307952881]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.8478247523}
          userData={{ name: "comb_selves2_main_table160.001" }}
        />
        <mesh
          name="comb_selves2_main_table160002"
          castShadow
          receiveShadow
          geometry={nodes.comb_selves2_main_table160002.geometry}
          material={materials.Brown}
          position={[378.5132751465, -328.6075439453, -216.6690673828]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.7292482257}
          userData={{ name: "comb_selves2_main_table160.002" }}
        />
        <mesh
          name="comb_selves2_main_table160003"
          castShadow
          receiveShadow
          geometry={nodes.comb_selves2_main_table160003.geometry}
          material={materials.Brown}
          position={[378.5132751465, -295.2342834473, -244.2791748047]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.7292482257}
          userData={{ name: "comb_selves2_main_table160.003" }}
        />
        <mesh
          name="comb_selves2_main_table160004"
          castShadow
          receiveShadow
          geometry={nodes.comb_selves2_main_table160004.geometry}
          material={materials.Brown}
          position={[379.0114440918, -252.0502624512, -222.9151916504]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.9573463202}
          userData={{ name: "comb_selves2_main_table160.004" }}
        />
        <mesh
          name="comb_selves2_main_table160005"
          castShadow
          receiveShadow
          geometry={nodes.comb_selves2_main_table160005.geometry}
          material={materials.Brown}
          position={[378.5132751465, -27.1888389587, -244.2792205811]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.7292482257}
          userData={{ name: "comb_selves2_main_table160.005" }}
        />
        <group
          name="Mesh8"
          position={[375.9493103027, -204.8112945557, -128.5516052246]}
          userData={{ name: "Mesh8" }}
        >
          <mesh
            name="Mesh002"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002.geometry}
            material={materials.Green}
          />
          <mesh
            name="Mesh002_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_1.geometry}
            material={materials.Yellow}
          />
          <mesh
            name="Mesh002_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_2.geometry}
            material={materials.Red}
          />
          <mesh
            name="Mesh002_3"
            castShadow
            receiveShadow
            geometry={nodes.Mesh002_3.geometry}
            material={materials.Brown}
          />
        </group>
        <mesh
          name="polySurface185"
          castShadow
          receiveShadow
          geometry={nodes.polySurface185.geometry}
          material={materials.White}
          position={[375.0692749023, -69.8222045898, -207.8686523438]}
          rotation={[0, 0, 0.1780235696]}
          scale={[0.8478248119, 0.8478248119, 0.8478247523]}
          userData={{ name: "polySurface185" }}
        />
        <mesh
          name="polySurface185001"
          castShadow
          receiveShadow
          geometry={nodes.polySurface185001.geometry}
          material={materials.White}
          position={[375.3282165527, -329.1716003418, -208.5302886963]}
          rotation={[0, 0, 0.1780235893]}
          scale={[0.7292483449, 0.7292483449, 0.7292482257]}
          userData={{ name: "polySurface185.001" }}
        />
        <mesh
          name="polySurface185002"
          castShadow
          receiveShadow
          geometry={nodes.polySurface185002.geometry}
          material={materials.White}
          position={[375.3282165527, -295.7983703613, -236.1403961182]}
          rotation={[0, 0, 0.1780235893]}
          scale={[0.7292483449, 0.7292483449, 0.7292482257]}
          userData={{ name: "polySurface185.002" }}
        />
        <mesh
          name="polySurface185003"
          castShadow
          receiveShadow
          geometry={nodes.polySurface185003.geometry}
          material={materials.White}
          position={[374.830078125, -252.7907867432, -212.230758667]}
          rotation={[0, 0, 0.1780235395]}
          scale={[0.957346499, 0.957346499, 0.9573463202]}
          userData={{ name: "polySurface185.003" }}
        />
        <mesh
          name="polySurface185004"
          castShadow
          receiveShadow
          geometry={nodes.polySurface185004.geometry}
          material={materials.White}
          position={[375.3282165527, -27.7528934479, -236.1404418945]}
          rotation={[0, 0, 0.1780235893]}
          scale={[0.7292483449, 0.7292483449, 0.7292482257]}
          userData={{ name: "polySurface185.004" }}
        />
        <mesh
          name="polySurface255001"
          castShadow
          receiveShadow
          geometry={nodes.polySurface255001.geometry}
          material={materials.Red}
          position={[404.4984741211, -205.5809326172, -163.9463043213]}
          rotation={[0, 0, 0.742425509]}
          userData={{ name: "polySurface255.001" }}
        />
        <mesh
          name="polySurface258001"
          castShadow
          receiveShadow
          geometry={nodes.polySurface258001.geometry}
          material={materials.Red}
          position={[398.7457275391, -211.4645385742, -161.8330688477]}
          rotation={[0, 0, 0.742425509]}
          userData={{ name: "polySurface258.001" }}
        />
        <mesh
          name="polySurface326"
          castShadow
          receiveShadow
          geometry={nodes.polySurface326.geometry}
          material={materials.Beige}
          position={[361.1992492676, -15.5214538574, -171.0353088379]}
          userData={{ name: "polySurface326" }}
        />
        <mesh
          name="polySurface327"
          castShadow
          receiveShadow
          geometry={nodes.polySurface327.geometry}
          material={materials.Yellow}
          position={[356.968963623, -30.1272296906, -167.8725738525]}
          userData={{ name: "polySurface327" }}
        />
        <mesh
          name="polySurface378"
          castShadow
          receiveShadow
          geometry={nodes.polySurface378.geometry}
          material={materials.Orange}
          position={[373.9550170898, -123.6119918823, -172.8210296631]}
          userData={{ name: "polySurface378" }}
        />
        <mesh
          name="polySurface378001"
          castShadow
          receiveShadow
          geometry={nodes.polySurface378001.geometry}
          material={materials.Orange}
          position={[401.9737854004, -193.9182739258, -148.3720245361]}
          userData={{ name: "polySurface378.001" }}
        />
      </group>
      <group
        name="room_base_comb_window"
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0099999998}
        userData={{ name: "room_base_comb_window" }}
      >
        <mesh
          name="room_BASE_no_backside_comb_window"
          castShadow
          receiveShadow
          geometry={nodes.room_BASE_no_backside_comb_window.geometry}
          material={materials.WallsYellow}
          position={[-136.807434082, 108.1625061035, -177.3609771729]}
          userData={{ name: "room_BASE_no_backside_comb_window" }}
        />
        <mesh
          name="room_BASE_no_backside_comb_window001"
          castShadow
          receiveShadow
          geometry={nodes.room_BASE_no_backside_comb_window001.geometry}
          material={materials.Brown}
          position={[419.9747924805, -159.0063018799, -232.4629058838]}
          userData={{ name: "room_BASE_no_backside_comb_window.001" }}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/game_assets/models/Kitchen_v002-transformed.glb");

export default memo(Kitchen);
