/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 garden_v003.glb --transform --precision=10 --shadows --keepnames --meta --types
*/

import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    garden: THREE.Mesh;
    pitchfork_collider: THREE.Mesh;
    hoe_collider: THREE.Mesh;
    spade_collider: THREE.Mesh;
    rake_collider: THREE.Mesh;
    old_clothing_01_collider: THREE.Mesh;
    old_clothing_02_collider: THREE.Mesh;
    wood_scraps_collider: THREE.Mesh;
    drawer_collider: THREE.Mesh;
    paint_cans_collider: THREE.Mesh;
    hat_01_collider: THREE.Mesh;
    hat_02_collider: THREE.Mesh;
    hat_03_collider: THREE.Mesh;
    scarecrow_hat_collider: THREE.Mesh;
    bucket_collider: THREE.Mesh;
    screwdriver_phillips_collider: THREE.Mesh;
    sun_glasses_collider: THREE.Mesh;
    gloves_collider: THREE.Mesh;
    wood_glue_collider: THREE.Mesh;
    seed_packets_collider: THREE.Mesh;
    screwdriver_slot_collider: THREE.Mesh;
  };
  materials: {
    VertexColors_PBR: THREE.MeshStandardMaterial;
    colliders: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/garden_v003-transformed.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="garden"
        castShadow
        receiveShadow
        geometry={nodes.garden.geometry}
        material={materials.VertexColors_PBR}
        position={[0.1345324218, 0.0302855372, 2.0220003128]}
        userData={{ name: "garden" }}
      />
      <mesh
        name="pitchfork_collider"
        castShadow
        receiveShadow
        geometry={nodes.pitchfork_collider.geometry}
        material={materials.colliders}
        position={[-1.6641558409, 0.3154364526, -2.0840113163]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "pitchfork_collider" }}
      />
      <mesh
        name="hoe_collider"
        castShadow
        receiveShadow
        geometry={nodes.hoe_collider.geometry}
        material={materials.colliders}
        position={[-1.6010184288, 0.3065988719, -2.0853722095]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "hoe_collider" }}
      />
      <mesh
        name="spade_collider"
        castShadow
        receiveShadow
        geometry={nodes.spade_collider.geometry}
        material={materials.colliders}
        position={[-1.5347768068, 0.2842642963, -2.0817008018]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "spade_collider" }}
      />
      <mesh
        name="rake_collider"
        castShadow
        receiveShadow
        geometry={nodes.rake_collider.geometry}
        material={materials.colliders}
        position={[-1.4088909626, 0.3542487025, -2.09096241]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "rake_collider" }}
      />
      <mesh
        name="old_clothing_01_collider"
        castShadow
        receiveShadow
        geometry={nodes.old_clothing_01_collider.geometry}
        material={materials.colliders}
        position={[-1.3045467138, 0.2986439764, -2.0216860771]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "old_clothing_01_collider" }}
      />
      <mesh
        name="old_clothing_02_collider"
        castShadow
        receiveShadow
        geometry={nodes.old_clothing_02_collider.geometry}
        material={materials.colliders}
        position={[-1.0051436424, 0.340031594, -1.9816286564]}
        rotation={[0.1484920688, -1.1292689857, 0.1639752526]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "old_clothing_02_collider" }}
      />
      <mesh
        name="wood_scraps_collider"
        castShadow
        receiveShadow
        geometry={nodes.wood_scraps_collider.geometry}
        material={materials.colliders}
        position={[-1.0871237516, 0.2542139888, -2.0084190369]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "wood_scraps_collider" }}
      />
      <mesh
        name="drawer_collider"
        castShadow
        receiveShadow
        geometry={nodes.drawer_collider.geometry}
        material={materials.colliders}
        position={[-1.1542903185, 0.1685494781, -1.8580577374]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "drawer_collider" }}
      />
      <mesh
        name="paint_cans_collider"
        castShadow
        receiveShadow
        geometry={nodes.paint_cans_collider.geometry}
        material={materials.colliders}
        position={[-1.1202626228, 0.083230257, -1.4815194607]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "paint_cans_collider" }}
      />
      <mesh
        name="hat_01_collider"
        castShadow
        receiveShadow
        geometry={nodes.hat_01_collider.geometry}
        material={materials.colliders}
        position={[-1.3018875122, 0.5209507346, -2.0035440922]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "hat_01_collider" }}
      />
      <mesh
        name="hat_02_collider"
        castShadow
        receiveShadow
        geometry={nodes.hat_02_collider.geometry}
        material={materials.colliders}
        position={[-1.0701175928, 0.5498154759, -1.6203159094]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "hat_02_collider" }}
      />
      <mesh
        name="hat_03_collider"
        castShadow
        receiveShadow
        geometry={nodes.hat_03_collider.geometry}
        material={materials.colliders}
        position={[-1.0699681044, 0.5500504375, -1.4651317596]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "hat_03_collider" }}
      />
      <mesh
        name="scarecrow_hat_collider"
        castShadow
        receiveShadow
        geometry={nodes.scarecrow_hat_collider.geometry}
        material={materials.colliders}
        position={[-1.046432972, 0.5645921826, -1.3202075958]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "scarecrow_hat_collider" }}
      />
      <mesh
        name="bucket_collider"
        castShadow
        receiveShadow
        geometry={nodes.bucket_collider.geometry}
        material={materials.colliders}
        position={[-1.2076330185, 0.1399183124, -1.2200758457]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "bucket_collider" }}
      />
      <mesh
        name="screwdriver_phillips_collider"
        castShadow
        receiveShadow
        geometry={nodes.screwdriver_phillips_collider.geometry}
        material={materials.colliders}
        position={[-1.0848414898, 0.2657630444, -1.5047278404]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "screwdriver_phillips_collider" }}
      />
      <mesh
        name="sun_glasses_collider"
        castShadow
        receiveShadow
        geometry={nodes.sun_glasses_collider.geometry}
        material={materials.colliders}
        position={[-1.0988767147, 0.2560735941, -1.6801595688]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "sun_glasses_collider" }}
      />
      <mesh
        name="gloves_collider"
        castShadow
        receiveShadow
        geometry={nodes.gloves_collider.geometry}
        material={materials.colliders}
        position={[-1.1080912352, 0.3244534135, -1.6478097439]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "gloves_collider" }}
      />
      <mesh
        name="wood_glue_collider"
        castShadow
        receiveShadow
        geometry={nodes.wood_glue_collider.geometry}
        material={materials.colliders}
        position={[-1.0907549858, 0.39123559, -1.453499794]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "wood_glue_collider" }}
      />
      <mesh
        name="seed_packets_collider"
        castShadow
        receiveShadow
        geometry={nodes.seed_packets_collider.geometry}
        material={materials.colliders}
        position={[-1.0744003057, 0.255734086, -1.3504766226]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "seed_packets_collider" }}
      />
      <mesh
        name="screwdriver_slot_collider"
        castShadow
        receiveShadow
        geometry={nodes.screwdriver_slot_collider.geometry}
        material={materials.colliders}
        position={[-1.1116843224, 0.1397005618, -1.8594522476]}
        scale={[0.5629749894, 2.5660336018, 0.5629749894]}
        userData={{ name: "screwdriver_slot_collider" }}
      />
    </group>
  );
}

useGLTF.preload("/garden_v003-transformed.glb");
