const GATE_FOV = 37;
const BIGTREE_FOV = 40;
const TOOLRACK_FOV = 40;
const PLANTBOX_FOV = 35;
const GARDENVIEW_FOV = 40;
const GARDENHOSE_FOV = 40;
const SOILCORNER_FOV = 30;
const KITCHENVIEW_FOV = 40;

export {
  GATE_FOV,
  BIGTREE_FOV,
  TOOLRACK_FOV,
  PLANTBOX_FOV,
  GARDENHOSE_FOV,
  SOILCORNER_FOV,
  GARDENVIEW_FOV,
  KITCHENVIEW_FOV,
};
