export const dummy_tiles = [
  {
    titleFirstLine: "Discover",
    titleSecondLine: "Together",
    titleColor: "orange-600",
    subtitle: "",
    gradientStart: "#FEE5DD",
    gradientEnd: "#FFF5CC",
    image: "/images/homepage/discover-together.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud Lorem ipsum do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud",
    buttonText: "Let's go!",
    buttonLink: "/dashboard/discover-together",
    buttonAction: "link",
    speechBubble: {
      left: 500,
      top: 90,
      variant: "orange",
      link: "discover-together",
      text: "Discover more",
    },
  },
  {
    titleFirstLine: "Grow",
    titleSecondLine: "Together",
    titleColor: "green-600",
    subtitle: "",
    gradientStart: "#D2F7E5",
    gradientEnd: "#FFF5CC",
    image: "/images/homepage/grow-together.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud Lorem ipsum do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud",
    buttonText: "Let's go!",
    buttonLink: "/dashboard/discover-together",
    buttonAction: "link",
    speechBubble: {
      left: 500,
      top: 90,
      variant: "orange",
      link: "grow-together",
      text: "Learn more about gardening",
    },
  },
  {
    titleFirstLine: "Cook",
    titleSecondLine: "Together",
    titleColor: "blue-600",
    subtitle: "",
    gradientStart: "#C4E8FF",
    gradientEnd: "#D2F7E5",
    image: "/images/homepage/cook-together.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud Lorem ipsum do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud",
    buttonText: "Let's go!",
    buttonLink: "/dashboard/cook-together",
    buttonAction: "link",
    speechBubble: {
      left: 500,
      top: 90,
      variant: "blue",
      link: "cook-together",
      text: "Learn more about cooking",
    },
  },
  {
    titleFirstLine: "Mad",
    titleSecondLine: "Kitchen",
    titleColor: "orange-600",
    subtitle: "Cook Chocolate",
    gradientStart: "#FEE5DD",
    gradientEnd: "#FFF5CC",
    image: "/images/homepage/mad-kitchen.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud Lorem ipsum do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud",
    buttonText: "Let's go!",
    buttonLink: "/dashboard/mad-kitchen",
    buttonAction: "link",
    speechBubble: {
      left: 500,
      top: 90,
      variant: "orange",
      link: "games",
      text: "Explore more games",
    },
  },
  {
    titleFirstLine: "foodways",
    titleSecondLine: "",
    titleColor: "green-600",
    subtitle: "Cook Chocolate",
    gradientStart: "#D2F7E5",
    gradientEnd: "#FFF5CC",
    image: "/images/homepage/foodways.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud Lorem ipsum do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud",
    buttonText: "Let's go!",
    buttonLink: "/dashboard/foodways",
    buttonAction: "link",
    speechBubble: {
      left: 500,
      top: 90,
      variant: "green",
      link: "foodways",
      text: "Explore more foodways",
    },
  },
  {
    titleFirstLine: "Mealtime",
    titleSecondLine: "Moments",
    titleColor: "blue-600",
    subtitle: "Cook Chocolate",
    gradientStart: "#C4E8FF",
    gradientEnd: "#D2F7E5",
    image: "/images/homepage/mealtime-moments.png",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud Lorem ipsum do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud",
    buttonText: "Let's go!",
    buttonLink: "/dashboard/mealtime-moments",
    buttonAction: "link",
    speechBubble: {
      left: 500,
      top: 90,
      variant: "blue",
      link: "mealtime-moments",
      text: "Explore more Mealtime Moments",
    },
  },
];

export const meal_planner_tile = {
  titleFirstLine: "Meal",
  titleSecondLine: "Planner",
  titleColor: "orange-600",
  subtitle: "Lettuce help you build a meal plan",
  gradientStart: "#FEE5DD",
  gradientEnd: "#FFF5CC",
  image: "/images/homepage/meal-planner.png",
  description:
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud Lorem ipsum do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud",
  buttonText: "Let's go!",
  buttonLink: "/dashboard/mealtime-moments",
  buttonAction: "link",
  speechBubble: {
    left: 500,
    top: 90,
    variant: "orange",
    link: "meal-planner",
    text: "Explore more Meal Planner",
  },
};
